# Generated by Django 4.1.2 on 2023-06-26 18:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('bio', models.TextField()),
                ('address_city', models.CharField(max_length=100, null=True)),
                ('address_state', models.CharField(max_length=50, null=True)),
                ('address_pin', models.CharField(max_length=10, null=True)),
                ('address_locality', models.CharField(blank=True, max_length=100)),
                ('registration_year', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)])),
                ('passing_out_year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2023), django.core.validators.MaxValueValidator(2035)])),
                ('department', models.CharField(choices=[('architecture', 'Architecture, Planning and Design'), ('ceramic', 'Ceramic Engineering'), ('chemical', 'Chemical Engineering'), ('civil', 'Civil Engineering'), ('computer', 'Computer Engineering'), ('electrical', 'Electrical Engineering'), ('electronics', 'Electronics Engineering'), ('mechanical', 'Mechanical Engineering'), ('metallurgical', 'Metallurgical Engineering'), ('mining', 'Mining Engineering'), ('pharmaceutical', 'Pharmaceutical Engineering & Technology'), ('biochemical', 'Biochemical Engineering'), ('biomedical', 'Biomedical Engineering'), ('materials', 'Materials Science and Technology'), ('chemistry', 'Chemistry'), ('physics', 'Physics'), ('math', 'Mathematical Sciences'), ('humanistic', 'Department of Humanistic Studies')], max_length=50, null=True)),
                ('contact_self', models.CharField(max_length=20, null=True)),
                ('contact_parents', models.CharField(blank=True, max_length=20)),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('security', 'Security Personnel')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
