# Generated by Django 4.2.3 on 2023-07-03 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidentreporting', '0003_incident_zone_alter_incident_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='other_type_description',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='zone',
        ),
    ]
