# Generated by Django 4.2.3 on 2023-07-03 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('incidentreporting', '0004_remove_incident_other_type_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='zone',
            field=models.CharField(choices=[('near LC', 'Near LC'), ('near gymkhana', 'Near Gymkhana'), ('near rajputana', 'Near Rajputana'), ('near newgirls hostel', 'Near Newgirls Hostel')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
